name: unit-test-flow.yml
on:
  pull_request:
    branches:
      - trunk

jobs:
  checkstyle-job:
    name: Testing | PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Run tests
        run: ./gradlew test
